### ISSUE TITLE
Modules updates

### ISSUE THREAD

**Issue by Bibi40k** [webkul/hotelcommerce#10]
Hi,
first of all, thanks for your work.

There is a list of 14th modules reported as old and i cannot update them. Is this normal, you restricted any kind of updates to prevent incompatibility issues ?

```
An upgrade is available for some of your modules!
Bank wire
Cart block
Currency block
Dashboard Goals
Dashboard Products
Dashboard Trends
Language selector block
My Account block
Newsletter block
Payment by check
Product Comments
Social networking block
Social sharing
User info block
```

**Comment by sumitwebkul** [comment]
Hello,
Thanks for the appreciation.
Please don't upgrade any module because many modules files are changed to make it compatible with a hotel reservation system from an e-commerce platform. Because if you upgrade all files will be overrided and the changes done in the files will be lost. Which will create issues in the working flow of Qloapps.

**Comment by webkul** [comment]
Hello Bibi40k
those report of updates are from the prestashop server . As we build this on forked prestashop version . we don't recommend to update any module from prestashop because making ecommerce suitable to Hotel industry we did lots of changes on Prestashop core . In newer versions you will get update only from qloapps
