### ISSUE TITLE
Customize Front End (Contact Us-Page)

### ISSUE THREAD

**Issue by yogichandras** [webkul/hotelcommerce#44]
Hello,

I need help, how can i edit contact description etc in Contact Us Page ?

![customize](https://user-images.githubusercontent.com/32407979/40885381-55cdf316-674f-11e8-95f0-db1e10f1d880.PNG)

 I've done edit that in theme folder/ contact-form.tpl , but nothing changes. 

Thank you.

**Comment by sumitwebkul** [comment]
You are editing the correct file (contact-form.tpl) to make changes in contact us page.
But the changes may not reflect because of the cache. So in development phase, We recommend to disable the cache. 
Please clear cache once and also disable the cache from Advance parameters->performance https://prnt.sc/jydhis.
To clear and disable cache, select Force Compilation for Template Compilation and disable the Cache field. Then click on save to save the settings https://prnt.sc/jydim0 .
