### ISSUE TITLE
Location Wise Search

### ISSUE THREAD

**Issue by Bibi40k** [webkul/hotelcommerce#9]
Hi,
first of all, thanks for your work.

if i have 2 hotels in the same location it forces me to chose one hotel instead of showing me all the available rooms from all hotels in that city. Can you please fix this ?

**Comment by priyanka200** [comment]
Hi,

Thanks for appreciating our work. 

As per our analysis of hotel industry, we have found that there are various ways to search the rooms to book on a hotel website and one of the way is to select a particular Hotel in a location so that End User can have the list of room types available in their desired time period for the selected hotel.
The way requested by you is also one of the among and we would love to assist you for the same. We request you to raise your issue at our ticket system - https://webkul.uvdesk.com/ so that we can have a proper communication regarding the same.

Hope to hear back soon from you.
