### ISSUE TITLE
adding more earch filters to main page

### ISSUE THREAD

**Issue by engehab87** [webkul/hotelcommerce#90]
HI, i need to add more search filters to the main page, for example the price range and the main Amenities.

is there a way within the settings or not ?

**Comment by faizansari-bd** [comment]
Hi @engehab87 
The feature you are asking for is not there in the default system. 
But as we know that QloApps is highly customizable so we can customize this feature in QloApps for you. 
Please raise a ticket so that we can have one on one discussion on your requirement here: https://webkul.uvdesk.com/en/customer/create-ticket/
